### ISSUE TITLE
Make sure that everything is ready for go live of solochain (with token swap) and create checklist

### ISSUE THREAD

**Issue by 0xlyd** [jurteam/jur-node#27]
Let's make sure that the output of this task is:

- [ ] asking all pending items/doubts for the go live
- [ ] supporting Suhail with the infrastructure tasks
- [ ] creating a checklist of steps for go live
